import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"

import Header from "../Components/Header"
import LotteryEntrance from "../Components/LotteryEntrance"
//import ManualHeader from "../Components/ManualHeader"
import styles from "../styles/Home.module.css"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Smart Contract Lottery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            Hello, Next!!
            <Header />
            <LotteryEntrance />
        </>
    )
}
